### ISSUE TITLE
Comandos não reconhecidos

### ISSUE THREAD

**Issue by ricatom** [resultsystems/monitor#2]
Olá, instalei como orientado, mas ao executar os comandos, recebo as mensagens abaixo

php artisan monitor:laravel
'tail' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

php artisan monitor:queries
'touch' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
'clear' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

Obs: windows 10

**Comment by emtudo** [comment]
Olá @ricardotomim, tail, touch e clear são um comandos do Linux, não irá funcionar no windows a menos que você tenha o bash nele, que é possível, mas eu fico te devendo porque não uso windows a mais de 10 anos, mas sei que existe o bash para windows, você precisa dele instalado.

**Comment by ricatom** [comment]
Blz @emtudo, grato
